#!/bin/sh
#SBATCH --partition=jupiter
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --gres=gpu:1
#SBATCH --mem=32G
#SBATCH --time=03-23:59:59
#SBATCH --job-name=SAFA_TR_res34_888_USA_sw
#SBATCH --output=%x_%j.out
#SBATCH --mail-user=xyli1905@bsbii.cn
#SBATCH --mail-type=ALL

python train.py \
--data_dir /OceanStor100D/home/zhouyi_lab/xyli1905/dataset/Dataset_/cross-view/CVUSA/ \
--dataset CVUSA \
--model SAFA_TR \
--SAFA_heads 8 \
--TR_heads 8 \
--TR_layers 8 \
--save_suffix USA_lessAUG_CF_sw \
--geo_aug strong \
--sem_aug weak \
--cf 