#!/bin/sh
#SBATCH --partition=jupiter
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --gres=gpu:1
#SBATCH --mem=32G
#SBATCH --time=03-23:59:59
#SBATCH --job-name=reg_TK_FFusion_test_ACT_rotate_best
#SBATCH --output=%x_%j.out
#SBATCH --mail-user=xyli1905@bsbii.cn
#SBATCH --mail-type=ALL

python regression.py \
--dataset CVACT \
--data_dir /OceanStor100D/home/zhouyi_lab/xyli1905/dataset/Dataset_/cross-view/CVACT/ \
--model TK_FFusion \
--load_model \
--model_path 1649643310_TK_FFusion_CVUSA_False_learn_pos_True__TK_FFusion \
--reg_mode rotate \
--model_mode best \
--suffix reg_TK_FFusion_test_ACT_rotate_best