#!/bin/sh
#SBATCH --partition=jupiter
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --gres=gpu:1
#SBATCH --mem=32G
#SBATCH --time=03-23:59:59
#SBATCH --job-name=reg_SAFA_TR_STR_initModel_ACT_rotate_no_sync_best
#SBATCH --output=%x_%j.out
#SBATCH --mail-user=xyli1905@bsbii.cn
#SBATCH --mail-type=ALL

python regression.py \
--dataset CVACT \
--data_dir /OceanStor100D/home/zhouyi_lab/xyli1905/dataset/Dataset_/cross-view/CVACT/ \
--model SAFA_TR \
--model_path SAFA_TR_STR_AUG_res34_best_model \
--reg_mode rotate \
--no_sync \
--model_mode best \
--suffix reg_STR_ACT_initModel_rotate_no_sync_best